import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
export const metadata = {
  title: 'Frontend Development Experience',
  description: 'Explore Aderibigbe Victor’s frontend engineering experience across healthcare, blockchain, fintech, agritech, e-commerce, consulting and education.',
  alternates: { canonical: '/testimonials/' },
  openGraph: { title: 'Frontend Development Experience — Aderibigbe Victor', url: '/testimonials/' }
};
const roles=[['Oct 2025—Sep 2026','Lead Frontend Developer','Von Newman Consulting','Developed software and frontend solutions for the consultancy.'],['Apr—Jul 2026','Freelance Frontend Developer','Medeet','Built hospital management dashboards for staff activity, patients, payments, appointments, and clinical user groups.'],['Feb—Dec 2025','Lead Frontend / SDK Developer','ToroAccess','Created SDK documentation, wallet interfaces, event-ticketing journeys, and Toronet RPC workflows while mentoring junior contributors.'],['Nov—Dec 2025','Freelance Frontend Engineer','PalmBloc','Built mobile-first stablecoin deposit and QR/SMS transfer interfaces with payment integrations.'],['2023—2025','Frontend Developer','Sprintat · Tizmine Farms · Cemperium · Luxe Autos','Delivered React interfaces, blockchain features, geolocation ordering, product APIs, reusable components, and Three.js visualisation.'],['2018—2025','IT Support & Training','Oyo State SUBEB · SQI College of ICT · Jubal Stores','Supported users, resolved software issues, maintained digital systems, and assisted web-development learners.']];
export default function ExperiencePage(){return <><SiteHeader /><main><section className="experience-page shell"><h1 className="display split-reveal">Experience across products, platforms, and people.</h1><p className="section-copy reveal">Verified roles and project work from consulting, healthcare, blockchain, fintech, agritech, e-commerce, support, and training.</p><div className="timeline">{roles.map(([date,title,company,copy])=><article className="reveal" key={company}><time>{date}</time><div><h2>{title}</h2><h3>{company}</h3><p>{copy}</p></div></article>)}</div></section></main><SiteFooter action="Start a conversation." /></>}
